# -*- coding: utf-8 -*-
"""201016_Lecture_01_Folium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vFVd45u98KrhHJdLqZKoOgmiXLKgnzVq
"""

import folium

pip install git+https://github.com/python-visualization/branca.git@master

"""### 위도 경도 위치 표시"""

# 위도, 경도 위치 표시
loc=folium.Map(location=[37.5556777,126.9685811],zoom_start=17) #zoom_start=0~18(def=10)
loc

loc.save('seoul_stn.html')

"""### 실습 1 : 임의의 좌표를 찍어 그 장소가 저장된 html 파일 저장"""

my_loc=folium.Map(location=[37.5600983,126.7304434])
my_loc.save('GMP.html')

"""### 지도의 위치 찍기(Marker)"""

m = folium.Map(
    location=[37.5466423,126.9092281],
    zoom_start=15
)

folium.Marker(
    location=[37.5466423,126.9092281],
    popup = 'yanghwajin',                         # 선택 시 popup
    icon = folium.Icon(color='red', icon='star')  # 아이콘 
).add_to(m)

m

"""### 실습 2. 마커를 이용해 임의의 주제로 5군데 찍어보기"""

m = folium.Map(
    location=[37.5398422,126.9995773],
    zoom_start=12
)

folium.Marker(
    location=[37.5575175,126.9237902],
    popup = '홍대',                         # 선택 시 popup
    icon = folium.Icon(color='red', icon='star')  # 아이콘 
).add_to(m)

folium.Marker(
    location=[37.5511736,126.9860379],
    popup = 'N서울타워',                         # 선택 시 popup
    icon = folium.Icon(color='yellow', icon='star')  # 아이콘 
).add_to(m)

folium.Marker(
    location=[37.5129949,127.1005435],
    popup = '롯데월드타워',                         # 선택 시 popup
    icon = folium.Icon(color='green', icon='star')  # 아이콘 
).add_to(m)

folium.Marker(
    location=[37.5796212,126.9748523],
    popup = '경복궁',                         # 선택 시 popup
    icon = folium.Icon(color='blue', icon='star')  # 아이콘 
).add_to(m)

folium.Marker(
    location=[37.4974087,127.0259273],
    popup = '강남역',                         # 선택 시 popup
    icon = folium.Icon(color='purple', icon='star')  # 아이콘 
).add_to(m)


m
m.save('Landmarks_Seoul.html')