# -*- coding: utf-8 -*-
"""201016_Lecture_03_DataStructure_review.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ketFlt2rxFV2_Kn68S7BDB48mwHSwrYq

### 배운 내용 복습
"""

myfood=['banana', 'apple', 'candy']

print(myfood[0])
print(myfood[1])
print(myfood[2])
print(myfood[1:3])

for item in myfood:
  print(item)

for item in enumerate(myfood):
  print(item)

dict1 = {'one':'하나', 'two':"둘", 'three':'셋'}
dict2 = {1:"하나", 2:"둘", 3:"셋"}
dict3 = {'col1':[1,2,3], 'col2':['a','b','c']}

"""### dict1 둘, dict2 셋, dict3 'b' 출력해보기"""

print(dict1['two'])
print(dict2[3])
print(dict3['col2'][1])

"""### Series 복습"""

from pandas import Series

score = Series( [1000, 14000, 3000], index=['2019-05-01','2019-05-02','2019-05-03'])
print(score) 
print("자료형 확인 : ", type(score))

gildong = Series([1500, 3000, 2500], 
                 index = ['2019-05-01', '2019-05-02', '2019-05-03'] )
toto = Series([3000, 3000, 2000], 
              index = ['2019-05-01', '2019-05-03', '2019-05-02'] )

"""### DataFrame 복습"""

from pandas import DataFrame

dat = { 'col1':[1,2,3,4], 
        'col2' : [10,20,30,40],
        'col3' : ['A', 'B', 'C', 'D'] }

df = DataFrame(dat)
df

"""### 네 팀의 5일간의 팀별 점수"""

team_score = { "toto":[1500,3000,5000,7000,5500],
              "apple":[4000,5000,6000,5500,4500],
              "gildong":[2000,2500,3000,4000,3000],
              "catanddog":[7000,5000,3000,5000,4000]}

team_df = DataFrame(team_score)
team_df

date = ['19-05-01','19-05-02', '19-05-03', '19-05-04', '19-05-05']
team_df = DataFrame(team_score,
                   columns=['catanddog', 'toto', 'apple', 'gildong'],
                   index=date)
team_df

"""### toto 팀의 일별 점수 알아보기"""

team_df['toto']

team_df.columns

# toto와 apple 열을 선택하고 싶다.
team_df[1:2]
team_df[['toto','apple']]

#2행 ~ 어디까지
team_df[1:4] # 2행 ~ 4행까지

# toto부터 gildong까지 선택하고싶다.
# 3~5행 데이터 선택
# [데이터셋].loc[행인덱스, 열의인덱스]
team_df.loc['19-05-03':'19-05-05', 'toto':'gildong']

# 행/열의 인덱스는 모른다
# 열을 선택하는데 첫번째 열부터 3번쨰 열까지

team_df.iloc[:,0:3]

# 행/열의 인덱스는 모른다
# 열을 선택하는데 세번째 열부터

team_df.iloc[:, 2: ]

# team_df[['toto','gildong]]
team_df.loc[:,['toto','gildong']]

# 모든 열 선택
# 3번째 행까지 값을 보고 싶다
team_df.iloc[:3,:]

"""### 데이터프레임 요약
* team_df.describe()
"""

team_df

